import { createHash } from "node:crypto";

/**
 * Decoding a sealed forward week.
 *
 * The workbook states the contract exactly, and this implements it and
 * nothing more:
 *
 *   payload = base64( JSON(values) XOR sha256('StyleVerse-AI-R2-Embargo-v1'
 *                                             | reveal_on | row_key) )
 *
 *   row_key, planning grain   brand_id|category_id|channel_id|region_id|iso_week
 *   row_key, style grain      brand_id|style_id|iso_week
 *
 *   field order, planning     demand_units, sales_units, net_revenue_inr,
 *                             returns_units, markdown_units, markdown_loss_inr,
 *                             closing_inventory_units, availability_ratio
 *
 * THIS IS AN EMBARGO, NOT ENCRYPTION -- the workbook says so itself, because
 * the key is derivable from the row. Its job is to make accidental leakage
 * into a backtest impossible and deliberate leakage visible in a diff. So the
 * date check is not a formality to be worked around; it is the entire point,
 * and it lives in the caller that runs unattended.
 *
 * WHY A WRONG KEY CANNOT CORRUPT THE FACT TABLE.
 *
 * This code could not be tested before the first reveal date, because testing
 * it means decoding, and decoding early is the one thing the embargo forbids.
 * Shipping an unverified decoder that writes to fact_demand_weekly would be
 * reckless -- a wrong derivation would fill the table with plausible-looking
 * numbers.
 *
 * So the decoder proves itself on every row instead of being trusted:
 *
 *   1. XOR output must be valid UTF-8 JSON. Random bytes are not.
 *   2. It must parse to an ARRAY.
 *   3. Its length must equal the field_count stored beside it.
 *   4. Every element must be a finite number or null.
 *
 * A wrong key fails (1) essentially always and cannot survive all four. The
 * caller writes only rows that pass, counts the rest, and reports them -- so
 * the failure mode is "nothing was revealed and the log says why", never
 * "the history now contains noise".
 */

const PREFIX = "StyleVerse-AI-R2-Embargo-V1";

/** The prefix as the workbook writes it. Case matters to sha256. */
const PREFIX_EXACT = "StyleVerse-AI-R2-Embargo-v1";

export type SealedRow = {
  id: number;
  grain: string;
  brand_id: string;
  iso_week: string;
  week_start: string;
  reveal_on: string;
  category_id: string | null;
  channel_id: string | null;
  region_id: string | null;
  style_id: string | null;
  encoded_payload_b64: string;
  payload_checksum: string | null;
  field_count: number | null;
};

export function rowKey(row: SealedRow): string {
  return row.grain === "sku"
    ? [row.brand_id, row.style_id, row.iso_week].join("|")
    : [
        row.brand_id,
        row.category_id,
        row.channel_id,
        row.region_id,
        row.iso_week,
      ].join("|");
}

function keystream(revealOn: string, key: string, prefix: string): Buffer {
  return createHash("sha256").update(`${prefix}|${revealOn}|${key}`).digest();
}

/**
 * Decode one sealed row, or return null if the result cannot be trusted.
 *
 * Null is not an error to be logged and ignored -- it means this row is not
 * safe to write, and the caller must leave the fact table alone.
 */
export function decodeSealed(row: SealedRow): number[] | null {
  const cipher = Buffer.from(row.encoded_payload_b64, "base64");
  if (cipher.length === 0) return null;

  // The prefix is documented in one case and the file was generated by
  // another tool; both are tried rather than assuming, and a wrong guess
  // simply fails the checks below.
  for (const prefix of [PREFIX_EXACT, PREFIX]) {
    const key = keystream(row.reveal_on, rowKey(row), prefix);
    const plain = Buffer.alloc(cipher.length);
    for (let i = 0; i < cipher.length; i += 1) {
      plain[i] = cipher[i] ^ key[i % key.length];
    }

    let parsed: unknown;
    try {
      parsed = JSON.parse(plain.toString("utf8"));
    } catch {
      continue; // random bytes are not JSON — wrong key
    }

    if (!Array.isArray(parsed)) continue;
    if (row.field_count !== null && parsed.length !== row.field_count) continue;

    const values = parsed.map((v) =>
      v === null ? null : typeof v === "number" && Number.isFinite(v) ? v : NaN,
    );
    if (values.some((v) => typeof v === "number" && Number.isNaN(v))) continue;

    return values as number[];
  }

  return null;
}

/** Planning-grain field order, from 30_Data_Dictionary. */
export const PLANNING_FIELDS = [
  "demand_units",
  "sales_units",
  "net_revenue_inr",
  "returns_units",
  "markdown_units",
  "markdown_loss_inr",
  "closing_inventory_units",
  "availability_ratio",
] as const;

/**
 * A decoded planning row as fact_demand_weekly holds it.
 *
 * returns_units is decoded and then dropped: fact_demand_weekly has no column
 * for it. Dropping a value the schema cannot hold is honest; inventing a
 * column for it during a reveal would not be.
 *
 * excluded_from_accuracy_scoring is derived here the same way it is for
 * history -- below the availability floor the week is demand-censored and
 * unscoreable -- so a revealed week enters the table under the identical rule
 * as the 104 weeks already in it.
 */
export function toFactRow(row: SealedRow, values: number[]) {
  const at = (name: (typeof PLANNING_FIELDS)[number]) =>
    values[PLANNING_FIELDS.indexOf(name)] ?? null;

  const availability = at("availability_ratio");

  return {
    iso_week: row.iso_week,
    week_start: row.week_start,
    brand_id: row.brand_id,
    category_id: row.category_id,
    channel_id: row.channel_id,
    region_id: row.region_id,
    demand_units_unconstrained: at("demand_units"),
    sales_units: at("sales_units"),
    availability_ratio: availability,
    net_revenue_inr: at("net_revenue_inr"),
    markdown_units: at("markdown_units"),
    markdown_loss_inr: at("markdown_loss_inr"),
    closing_inventory_units: at("closing_inventory_units"),
    manual_baseline_forecast_units: null,
    excluded_from_accuracy_scoring:
      availability !== null && availability < 0.95,
  };
}
